version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: app-test-db:1.0
    networks:
      - backend    
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=pc
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    command: --default-authentication-plugin=mysql_native_password
    restart: always        
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: app-test-backend:1.0
    networks:
      - backend
      - frontend
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  frontend:
    build:
      context: ../024_docker-compose.yml
      dockerfile: Dockerfile.frontend
    networks:
      - frontend      
    depends_on:
      - backend
    image: app-test-frontend:1.0
    ports: 
      - "80:80"
    restart: always

volumes:
  mysql:
networks:
  frontend:
  backend:          
